0:
    friendlyname:
      NOR: Strandsnegl
      ENG: Common Periwinkle
      FRA: Bigorneau
      SPA: Bigaro
      NLD: Alikruik
    scientificname: Littorina littorea
    productionmethod: Handpicked
    gtin: 7072773000009
    grades:
      - 0: Unsorted
        pcs: N/A #/kg
      - 1: Medium
        pcs: 240+ #/kg
      - 2: Large
        pcs: 180-240 #/kg
      - 3: Jumbo
        pcs: 140-180 #/kg
      - 4: Super Jumbo
        pcs: 90-140 #/kg
    processing:
      - Climbed
      - Not climbed
1:
    friendlyname:
      NOR: Green Sea Urchin
      ENG: Green Sea Urchin
      FRA: Oursin Vert
      SPA: Erizo de mar verde
      NLD: Groene Zee-egel
    scientificname: Strongylocentrotus droebachiensis
    productionmethod: Handpicked
    gtin: 7072773000016
    grades:
      - 0: Unsorted
        pcs: N/A #/kg
      - 1: Medium
        pcs: 10-16 #/kg
      - 2: Large
        pcs: <10 #/kg
    processing:
      - N/A
2:
    friendlyname:
      NOR: Surprise box
      ENG: Surprise box
      FRA: Surprise box
      SPA: Surprise box
      NLD: Surprise box
    scientificname: NA
    productionmethod: NA
    gtin: 7072773000092
    grades:
      - 0: Unsorted
        pcs: N/A #/kg
    processing:
      - N/A
3:
    friendlyname:
      NOR: Hjerteskjell
      ENG: Cockle
      FRA: Coque
      SPA: Berberechos
      NLD: Kokkel
    scientificname: Cerastoderma edule
    productionmethod: Handpicked
    gtin: 7072773000054
    grades:
      - 0: Unsorted
        pcs: N/A #/kg
      - 1: Medium
        pcs: N/A #/kg
      - 2: Large
        pcs: N/A #/kg
    processing:
      - N/A
4:
    friendlyname:
      NOR: Sjøkreps
      ENG: Norway lobster
      FRA: Langoustine
      SPA: Cigala
      NLD: Noors kreeftje
    scientificname: Nephrops norvegicus
    productionmethod: Creel-fished
    gtin: 7072773000061
    grades:
      - 0: Unsorted
        pcs: N/A #/kg
      - 1: Small
        pcs: 12+ #/kg
      - 2: Medium
        pcs: 8-12 #/kg
      - 3: Large
        pcs: 4-8 #/kg
      - 4: Extra large
        pcs: 2-4 #/kg
    processing:
      - N/A
5:
    friendlyname:
      NOR: Albusnegl
      ENG: Common limpet
      FRA: Patelle commune
      SPA: Lapa común
      NLD: Gewone schaalhoren
    scientificname: Patella vulgata
    productionmethod: Handpicked
    gtin: 7072773000078
    grades:
      - 0: Unsorted
        pcs: N/A #/kg
    processing:
      - N/A